export const TRANSACTION_TYPES = {
  TOPUP: 'TOPUP',
  ADD_FUNDS: 'ADD_FUNDS',
  ESCROW_LOCK: 'ESCROW_LOCK',
  ESCROW_RELEASE: 'ESCROW_RELEASE',
  WITHDRAWAL: 'WITHDRAWAL',
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  REFUND: 'REFUND',
  PLATFORM_FEE: 'PLATFORM_FEE',
  PAYOUT: 'PAYOUT',
  DEPOSIT: 'DEPOSIT',
  ESCROW_HOLD: 'ESCROW_HOLD',
  ESCROW_REFUND: 'ESCROW_REFUND',
} as const;

export const PAYMENT_ORDER_PURPOSES = {
  WALLET_TOPUP: 'WALLET_TOPUP',
  ESCROW_FUND: 'ESCROW_FUND',
} as const;

export const TRANSACTION_STATUSES = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const ESCROW_STATUSES = {
  PENDING: 'PENDING',
  HELD: 'HELD',
  IN_PROGRESS: 'IN_PROGRESS',
  REVIEW: 'REVIEW',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  DISPUTED: 'DISPUTED',
} as const;

export const DELIVERABLE_STATUSES = {
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  IN_REVIEW: 'IN_REVIEW', // legacy alias for SUBMITTED
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const AUTO_RELEASE_DAYS = 7;

export const PLATFORM_FEE_PERCENT = Number(process.env.PLATFORM_FEE_PERCENT ?? 10);

export const DISPUTE_STATUSES = {
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  RESOLVED: 'RESOLVED',
  REFUNDED: 'REFUNDED',
  ESCALATED: 'ESCALATED', // legacy alias for IN_REVIEW
} as const;

export const WITHDRAWAL_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED', // legacy alias for APPROVED
} as const;

export const OPEN_DISPUTE_STATUSES = [
  DISPUTE_STATUSES.OPEN,
  DISPUTE_STATUSES.IN_REVIEW,
  DISPUTE_STATUSES.ESCALATED,
];

export const PAYMENT_ORDER_STATUSES = {
  CREATED: 'CREATED',
  PAID: 'PAID',
  FAILED: 'FAILED',
} as const;
