export const TRANSACTION_TYPES = {
  ADD_FUNDS: 'ADD_FUNDS',
  ESCROW_LOCK: 'ESCROW_LOCK',
  ESCROW_RELEASE: 'ESCROW_RELEASE',
  WITHDRAWAL: 'WITHDRAWAL',
  REFUND: 'REFUND',
  PAYOUT: 'PAYOUT',
  // Legacy aliases kept for backward compatibility
  DEPOSIT: 'DEPOSIT',
  ESCROW_HOLD: 'ESCROW_HOLD',
  ESCROW_REFUND: 'ESCROW_REFUND',
} as const;

export const TRANSACTION_STATUSES = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const ESCROW_STATUSES = {
  HELD: 'HELD',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  DISPUTED: 'DISPUTED',
} as const;

export const DISPUTE_STATUSES = {
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  RESOLVED: 'RESOLVED',
  REFUNDED: 'REFUNDED',
  ESCALATED: 'ESCALATED', // legacy alias for IN_REVIEW
} as const;

export const WITHDRAWAL_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED', // legacy alias for APPROVED
} as const;

export const OPEN_DISPUTE_STATUSES = [
  DISPUTE_STATUSES.OPEN,
  DISPUTE_STATUSES.IN_REVIEW,
  DISPUTE_STATUSES.ESCALATED,
];

export const PAYMENT_ORDER_STATUSES = {
  CREATED: 'CREATED',
  PAID: 'PAID',
  FAILED: 'FAILED',
} as const;
